# Generated by Django 4.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sent_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
